# Site settings
title: mashed note
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Molecular Dynamics をやっている院生の個人的なメモです。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  mash-it

# Build settings
markdown: kramdown
