# Site settings
title: mashed note
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Molecular Dynamics をやっている院生の個人的なメモです。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mash-it.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  mash-it

# Build settings
# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

permalink: none
# http://stackoverflow.com/questions/16099153/table-not-render-when-use-redcarpet-in-jekyll-github-pages
